Fix Support for Other Source and Playlist Types
cloudwithax/pomice pull request #69
Opened 2024-08-17 05:44 UTC by ZandercraftGames

Given Lavalink's support for track types beyond the hard-coded ones as well as the more recent adoption of plugins like LavaSrc to add more sources, this update adds support for a generic `OTHER` type on both `enums.TrackType` and `enums.PlaylistType`.

When an unsupported value is found, it will default it to the `OTHER` type, meaning that it maintains the existing enum structure, providing support for more specialized functionality, while also allowing for a catch-all with the caveat that behaviour is largely undefined from the library's standpoint.

Additionally, I added websockets as a dependency to the Pipfile since it was missing.

2024-08-17 08:49 UTC, NiceAesth requested changes
so mypy doesn't start screaming

2024-08-17 08:49 UTC, NiceAesth commented on pomice/enums.py
> +    def _missing_(cls, value):
```suggestion
    def _missing_(cls, _: object) -> "TrackType":
```

2024-08-17 08:49 UTC, NiceAesth commented on pomice/enums.py
> +    def _missing_(cls, value):
```suggestion
    def _missing_(cls, _: object) -> "PlaylistType":
```

2024-08-17 09:13 UTC, ZandercraftGames commented
> so mypy doesn't start screaming

Good catch. Thanks!

2024-08-24 01:04 UTC, cloudwithax commented
lgtm

2024-08-24 01:04 UTC, merged